# Generated by Django 3.0.5 on 2020-07-08 22:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_products/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MrMilk.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MrMilk.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='if phone number start with zero then 11 digits, else it checks 10 digits.', regex='^[0][1-9]\\d{9}$|^[1-9]\\d{9}$')])),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('no_of_days_left', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('sunday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('monday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('tuesday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('wednesday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('thursday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('friday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('saturday', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MrMilk.Product')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MrMilk.SubCategory'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000)])),
                ('order_status', models.CharField(choices=[('PL', 'PLACED'), ('SH', 'SHIPPED'), ('DL', 'DELIVERED')], default='PL', max_length=2)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 7, 8, 22, 50, 33, 762643, tzinfo=utc))),
                ('delivery_date', models.DateField(default=datetime.datetime(2020, 7, 9, 22, 50, 33, 762669, tzinfo=utc))),
                ('order_address', models.CharField(blank=True, max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('cod', models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=2)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MrMilk.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MrMilk.Product')),
            ],
            options={
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
