# Generated by Django 3.0.5 on 2020-07-08 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MrMilk', '0002_auto_20200709_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 9, 22, 52, 28, 471998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 22, 52, 28, 471961, tzinfo=utc)),
        ),
    ]
