# Generated by Django 3.1.1 on 2020-09-27 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MrMilk', '0010_auto_20200730_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 28, 12, 4, 59, 287968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 12, 4, 59, 287861, tzinfo=utc)),
        ),
    ]
